### ISSUE TITLE
Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference

### ISSUE THREAD

**Issue by ChrisSun99** [TonyDandelion/DemoforCamera2#1]
Hello! I'm wondering if you have experienced the nullPointerException on `surfaceview = (SurfaceView)view.findViewById(R.id.surfaceview_show_rectangle);` in `onViewCreated()`.
It is very strange that it executes `view.findViewById(R.id.picture).setOnClickListener(this);` and `view.findViewById(R.id.info).setOnClickListener(this);` without any problem but not `R.id.surfaceview_show_rectangle`. Below is the error message. 
<img width="1167" alt="Screen Shot 2019-07-25 at 3 18 37 PM" src="https://user-images.githubusercontent.com/40011864/61853880-7e3f3880-aeef-11e9-96b8-c53802cb0d68.png">

**Comment by TonyDandelion** [comment]
Have you modify any code in the layout code file(DemoforCamera2/Application/src/main/res/layout/fragment_camera2_basic.xml)?

Do you forgot decaring a SurfaceView in the layout code file and that's maybe the reason you have this problem. Please check in the surfaceview whether in your fragment_camera2_basic.xml.

**Comment by mengtis** [comment]
I didn't modify the xml file. Actually, I'm running this program on Zenbo robot instead of a mobile phone. I'm not sure if the hardware could be the reason. 
<img width="1188" alt="Screen Shot 2019-07-26 at 12 17 44 PM" src="https://user-images.githubusercontent.com/40011864/61925575-89ea3800-af9f-11e9-83b1-8ecbd24b6548.png">

**Comment by TonyDandelion** [comment]
I'm so sorry that I am not a professional android developer. Acorrding to your erro logs. When execute the code "surfaceview.setZOrderOnTop(true);",  JVM found that there is no any surfaceview object. I guess two different reason for this situation.
1. Hardware issue:the developed smartphone I used is huawei mate 9(https://consumer.huawei.com/en/support/phones/mate9/). And I wrote some special code for fit its' camera and screen. Maybe this is the reason you could have the problem.
2. Camera2 Version: Actually I have used the second version of Android Camera API for this program((https://developer.android.com/reference/android/hardware/camera2/package-summary) ). Different version of Android Camera have different API. Have you used the Camera2 too in the project? Please make sure you have the correct version of the libs.

**Comment by TonyDandelion** [comment]
A step in my code is to redraw the recognition results from Neural network to the display screen of the phone. Given the actual situation of zenbot, even though zenbot is running Android. But programmers are not allowed to make adjustments on its display as the same way in android phone.

**Comment by mengtis** [comment]
Thank you Tony! It was not the problem with your code. I asked Asus and they told me that I should use SurfaceTexture instead of SurfaceView which is an older version. It was the problem with the robot itself. Your code looks great!
